name: Docker

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

jobs:
  docker:
    uses: janw/workflows/.github/workflows/docker.yaml@main
    with:
      build-platforms: linux/amd64,linux/arm64/v8
      skip-hadolint: true
      tag-latest: true
